### ISSUE TITLE
New version 1.13.1 error in ES 7.17.4

### ISSUE THREAD

**Issue by guillermoc-infocorp** [fbaligand/kibana-enhanced-table#276]
Hi there! 
I have recently migrated from 7.12 to 7.17.4 following all the steps according to my previous experiences, I get an error when trying to access a dashboard with a enhanced table. It also has an error when trying to add a new table. I setup a new local empty environment, and the error has been replicated.

Error: [$injector:modulerr] Failed to instantiate module kibana/enhanced_table_vis due to:
Error: [$injector:modulerr] Failed to instantiate module tableVisI18n due to:
Error: [$injector:pget] Provider 'i18n' must define $get factory method.

https://errors.angularjs.org/1.8.2/$injector/modulerr?p0=kibana%2Fenhanced_table_vis&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20tableVisI18n%20due%20to%3A%0AError%3A%20%5B%24injector%3Apget%5D%20Provider%20'i18n'%20must%20define%20%24get%20factory%20method.%0A%0Ahttps%3A%2F%2Ferrors.angularjs.org%2F1.8.2%2F%24injector%2Fmodulerr%3Fp0%3DtableVisI18n%26p1%3DError%253A%2520%255B%2524injector%253Apget%255D%2520Provider%2520'i18n'%2520must%2520define%2520%2524get%2520factory%2520method.%250Ahttps%253A%252F%252Ferrors.angularjs.org%252F1.8.2%252F%2524injector%252Fpget%253Fp0%253Di18n%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fnb-guillec%253A5602%252F46909%252Fbundles%252Fplugin%252FenhancedTable%252F1.13.1%252FenhancedTable.chunk.1.js%253A14%253A837%250A%2520%2520%2520%2520at%2520g%2520(http%253A%252F%252Fnb-guillec%253A5602%252F46909%252Fbundles%252Fplugin%252FenhancedTable%252F1.13.1%252FenhancedTable.chunk.1.js%253A14%253A24743)%250A%2520%2520%2520%2520at%2520Object.provider%2520(http%253A%252F%252Fnb-guillec%253A5602%252F46909%252Fbundles%252Fplugin%252FenhancedTable%252F1.13.1%252FenhancedTable.chunk.1.js%253A14%253A24641)%250A%2520%2520%2520%2520at%2520r%2520(http%253A%252F%252Fnb-guillec%253A5602%252F46909%252Fbundles%252Fplugin%252FenhancedTable%252F1.13.1%252FenhancedTable.chunk.1.js%253A14%253A25607)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fnb-guillec%253A5602%252F46909%252Fbundles%252Fplugin%252FenhancedTable%252F1.13.1%252FenhancedTable.chunk.1.js%253A14%253A25233%250A%2520%2520%2520%2520at%2520k%2520(http%253A%252F%252Fnb-guillec%253A5602%252F46909%252Fbundles%252Fplugin%252FenhancedTable%252F1.13.1%252FenhancedTable.chunk.1.js%253A14%253A1542)%250A%2520%2520%2520%2520at%2520%2524%2520(http%253A%252F%252Fnb-guillec%253A5602%252F46909%252Fbundles%252Fplugin%252FenhancedTable%252F1.13.1%252FenhancedTable.chunk.1.js%253A14%253A25111)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fnb-guillec%253A5602%252F46909%252Fbundles%252Fplugin%252FenhancedTable%252F1.13.1%252FenhancedTable.chunk.1.js%253A14%253A25197%250A%2520%2520%2520%2520at%2520k%2520(http%253A%252F%252Fnb-guillec%253A5602%252F46909%252Fbundles%252Fplugin%252FenhancedTable%252F1.13.1%252FenhancedTable.chunk.1.js%253A14%253A1542)%250A%2520%2520%2520%2520at%2520%2524%2520(http%253A%252F%252Fnb-guillec%253A5602%252F46909%252Fbundles%252Fplugin%252FenhancedTable%252F1.13.1%252FenhancedTable.chunk.1.js%253A14%253A25111)%0A%20%20%20%20at%20http%3A%2F%2Fnb-guillec%3A5602%2F46909%2Fbundles%2Fplugin%2FenhancedTable%2F1.13.1%2FenhancedTable.chunk.1.js%3A14%3A837%0A%20%20%20%20at%20http%3A%2F%2Fnb-guillec%3A5602%2F46909%2Fbundles%2Fplugin%2FenhancedTable%2F1.13.1%2FenhancedTable.chunk.1.js%3A14%3A25436%0A%20%20%20%20at%20k%20(http%3A%2F%2Fnb-guillec%3A5602%2F46909%2Fbundles%2Fplugin%2FenhancedTable%2F1.13.1%2FenhancedTable.chunk.1.js%3A14%3A1542)%0A%20%20%20%20at%20%24%20(http%3A%2F%2Fnb-guillec%3A5602%2F46909%2Fbundles%2Fplugin%2FenhancedTable%2F1.13.1%2FenhancedTable.chunk.1.js%3A14%3A25111)%0A%20%20%20%20at%20http%3A%2F%2Fnb-guillec%3A5602%2F46909%2Fbundles%2Fplugin%2FenhancedTable%2F1.13.1%2FenhancedTable.chunk.1.js%3A14%3A25197%0A%20%20%20%20at%20k%20(http%3A%2F%2Fnb-guillec%3A5602%2F46909%2Fbundles%2Fplugin%2FenhancedTable%2F1.13.1%2FenhancedTable.chunk.1.js%3A14%3A1542)%0A%20%20%20%20at%20%24%20(http%3A%2F%2Fnb-guillec%3A5602%2F46909%2Fbundles%2Fplugin%2FenhancedTable%2F1.13.1%2FenhancedTable.chunk.1.js%3A14%3A25111)%0A%20%20%20%20at%20Xe%20(http%3A%2F%2Fnb-guillec%3A5602%2F46909%2Fbundles%2Fplugin%2FenhancedTable%2F1.13.1%2FenhancedTable.chunk.1.js%3A14%3A24440)%0A%20%20%20%20at%20i%20(http%3A%2F%2Fnb-guillec%3A5602%2F46909%2Fbundles%2Fplugin%2FenhancedTable%2F1.13.1%2FenhancedTable.chunk.1.js%3A14%3A10355)%0A%20%20%20%20at%20Object.Tt%20%5Bas%20bootstrap%5D%20(http%3A%2F%2Fnb-guillec%3A5602%2F46909%2Fbundles%2Fplugin%2FenhancedTable%2F1.13.1%2FenhancedTable.chunk.1.js%3A14%3A10670)
    at http://nb-guillec:5602/46909/bundles/plugin/enhancedTable/1.13.1/enhancedTable.chunk.1.js:14:837
    at http://nb-guillec:5602/46909/bundles/plugin/enhancedTable/1.13.1/enhancedTable.chunk.1.js:14:25436
    at k (http://nb-guillec:5602/46909/bundles/plugin/enhancedTable/1.13.1/enhancedTable.chunk.1.js:14:1542)
    at $ (http://nb-guillec:5602/46909/bundles/plugin/enhancedTable/1.13.1/enhancedTable.chunk.1.js:14:25111)
    at Xe (http://nb-guillec:5602/46909/bundles/plugin/enhancedTable/1.13.1/enhancedTable.chunk.1.js:14:24440)
    at i (http://nb-guillec:5602/46909/bundles/plugin/enhancedTable/1.13.1/enhancedTable.chunk.1.js:14:10355)
    at Object.Tt [as bootstrap] (http://nb-guillec:5602/46909/bundles/plugin/enhancedTable/1.13.1/enhancedTable.chunk.1.js:14:10670)
    at EnhancedTableVisualizationController.getInjector (http://nb-guillec:5602/46909/bundles/plugin/enhancedTable/1.13.1/enhancedTable.chunk.1.js:65:46197)
    at http://nb-guillec:5602/46909/bundles/plugin/enhancedTable/1.13.1/enhancedTable.chunk.1.js:65:46896
    at new Promise (<anonymous>)

**Comment by fbaligand** [comment]
Hi,

I just tested and reproduced your issue.
That's very surprising, since plugin code is the same for Kibana 7.17.0 to 7.17.4. And it works on previous patch versions...
I will look to fix this issue.

**Comment by fbaligand** [comment]
Hi @guillermoc-infocorp,

This issue is fixed in last release:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.13.2
