### ISSUE TITLE
Trying to install enhanced-table-1.13.3_osd-2.2.0.zip in opensearch dashboards 2.2.0 but getting error.

### ISSUE THREAD

**Issue by Rajeshdaneti** [fbaligand/kibana-enhanced-table#297]
Hi All,
Trying to install enhanced-table-1.13.3_osd-2.2.0.zip in opensearch dashboards 2.2.0 but getting following error- 
Please assist me in solving the problem.

[opensearch-dashboards@opensearch-dashboards-86495f9499-6c8jj ~]$ bin/opensearch-dashboards-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.13.3/enhanced-table-1.13.3_osd-2.2.0.zip
Found previous install attempt. Deleting...
Attempting to transfer from https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.13.3/enhanced-table-1.13.3_osd-2.2.0.zip

/usr/share/opensearch-dashboards/src/cli_plugin/lib/log_warnings.js:45
    logger.error(warning);
           ^
TypeError: logger.error is not a function
    at process.<anonymous> (/usr/share/opensearch-dashboards/src/cli_plugin/lib/log_warnings.js:45:12)
    at process.emit (events.js:400:28)
    at process.emit (/usr/share/opensearch-dashboards/node_modules/source-map-support/source-map-support.js:516:21)
    at doEmitWarning (internal/process/warning.js:70:11)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
	
Regards
Rajesh

**Comment by fbaligand** [comment]
I close this issue as it is a duplicate from discussion #298
