### ISSUE TITLE
Error: Cannot access 'At' before initialization

### ISSUE THREAD

**Issue by tiagofga** [fbaligand/kibana-enhanced-table#343]
I installed Kibana version 8.12.1 and enhancedTable version v1.14.0.

When I import the dashboards and when I try to create a new panel (using Enhanced Table) generates the following error:

```
ReferenceError: Cannot access 'At' before initialization
    at EnhancedTableVisualizationController.initLocalAngular (http://<IP>:5601/70228/bundles/plugin/enhancedTable/1.14.0/enhancedTable.chunk.1.js:31:61634)
    at async EnhancedTableVisualizationController.render (http://<IP>:5601/70228/bundles/plugin/enhancedTable/1.14.0/enhancedTable.chunk.1.js:31:61775)
    at async expression_renderer_ExpressionRenderer.render (http://<IP>:5601/70228/bundles/plugin/enhancedTable/1.14.0/enhancedTable.plugin.js:1:33515)
    at async render_ExpressionRenderHandler.render (http://<IP>:5601/70228/bundles/plugin/expressions/1.0.0/expressions.plugin.js:1:95996)
```

The same indexes in Kibana 7.17.7 and enhancedTable version 1.13.3 are normal.

**Comment by fbaligand** [comment]
Hi @tiagofga,

I just downloaded Kibana 8.12.1 and tested with Enhanced Table plugin v1.14.0, and it works fine.

So I have some questions for you:
- did you install the exact package for Kibana v8.12.1, I mean: 
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.14.0/enhanced-table-1.14.0_8.12.1.zip
- I precise that you can get this error if you use package for Kibana 8.12.0
- Did you install the plugin using instructions here?
https://github.com/fbaligand/kibana-enhanced-table?tab=readme-ov-file#install
- Did you try to fully remove your browser cache (using Ctrl+Shift+Suppr in Chrome/Firefox) and then Shift + "Refresh Button" in your browser?

**Comment by tiagofga** [comment]
I apologize for what happened. I tried to install a previous version and didn't see the correct one.

I installed the indicated version and it works normally.

Thank you for your attention.

**Comment by fbaligand** [comment]
Nice! Thanks for the feedback! Enjoy the plugin 😉
