### ISSUE TITLE
Kibana Enhanced Table issue after upgrade to 8.15.2

### ISSUE THREAD

**Issue by AH-Amal** [fbaligand/kibana-enhanced-table#352]
Hello,

I have upgraded my ELK cluster to version 8.15.2 and post upgrade the Kibana enhanced tables are not loading properly. I have added the error message which I'm getting below. Kindly help me on this.

ReferenceError: Cannot access 'kt' before initialization
at EnhancedTableVisualizationController.initLocalAngular (https://observability-platform-tst.xxxxx.com/5a522bfe14bc/bundles/plugin/enhancedTable/1.14.0/enhancedTable.chunk.1.js:31:61880)
at async EnhancedTableVisualizationController.render (https://observability-platform-tst.xxxxx.com/5a522bfe14bc/bundles/plugin/enhancedTable/1.14.0/enhancedTable.chunk.1.js:31:62021)
at async expression_renderer_ExpressionRenderer.render (https://observability-platform-tst.xxxxx.com/5a522bfe14bc/bundles/plugin/enhancedTable/1.14.0/enhancedTable.plugin.js:1:160591)
at async render_ExpressionRenderHandler.render (https://observability-platform-tst.xxxxx.com/5a522bfe14bc/bundles/plugin/expressions/1.0.0/expressions.plugin.js:1:97066)

<img width="952" alt="Screenshot 2024-10-16 105350" src="https://github.com/user-attachments/assets/d5a8495b-ac59-4d1b-b593-6598a4625aaf">

Thanks,
Amal Varghese

**Comment by fbaligand** [comment]
Hi,
Thanks for your feedback.
It’s nice to see that you finally find a solution that works. 
that said, that is exactly what I did. This is why I’m very surprised that the published package does not work and yours works. 
As you say that your package works, I will replace the currently published one by yours. 
Are you OK with this?

**Comment by saman-jafari** [comment]
Sure, no problem at all, happy to help 😃

**Comment by fbaligand** [comment]
Hi @saman-jafari,

I found what was the problem in my package script and fixed it.
It impacted 8.15.1, 8.15.2, and 8.15.3.

I just rebuilt 8.15.1, and 8.15.3.
Finally, I published these two versions, plus your 8.15.2 package here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.14.0

Thanks for your help!
